site:
  title: ProgTech / DevTools
  start_page: aut-2026::index.adoc

content:
  sources:
    - url: .
      branches: [ '*' ]
ui:
  bundle:
    url: https://github.com/devtools-course/antora-ui/releases/download/latest/ui-bundle.zip
#    url: /home/nbah/antora-ui-default/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    experimental: ''
    page-pagination: ''
    allow-uri-read: ''
    source-highlighter: shiki
  extensions:
    - ./lib/remote-include-processor.js

antora:
  extensions:
    - require: 'antora-shiki-extension'
      use_line_numbers: true
      theme: taekwandodo-light
      languages:
        - java
        - cpp
        - c
        - bash
        - console
        - json
        - xml
        - yaml

    - require: '@antora/lunr-extension'
      languages: [en, ru]

#runtime:
#  fetch: true
